# Change these first
owner: binkhq # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Website
    url: https://www.bink.com/
  - name: API
    url: https://api.bink.com/ping

status-website:
  cname: status.bink.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Bink Status"
  introMessage: "Status of all Bink live services"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
