owner: zyntrixio
repo: upptime

sites:
  - name: Website
    url: https://www.zyntrix.io/
  - name: API
    url: https://api.zyntrix.io/ping

assignees:
  - cpressland

status-website:
  cname: status.zyntrix.io
  logoUrl: https://logos.bink.com/img/logos/checkmark-primary.png
  name: Upptime
  introTitle: "Zyntrix Status"
  themeUrl: https://status.zyntrix.io/catppuccin.css
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
