owner: binkhq
repo: upptime

sites:
  - name: Website
    url: https://www.bink.com/
  - name: API
    url: https://api.bink.com/ping

assignees:
  - cpressland

status-website:
  cname: status.bink.com
  logoUrl: https://logos.bink.com/img/logos/checkmark-primary.png
  name: Upptime
  introTitle: "Bink Status"
  themeUrl: https://status.bink.com/catppuccin.css
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
